import type { AuthenticatorTransportFuture } from "@simplewebauthn/server";
import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import type { ULID } from "@/lib/ulid";

////////////////////////////////////
// Common COLUMNS
////////////////////////////////////

const ulid = (...args: Parameters<typeof text>) => text(...args).$type<ULID>();
const createdAt = integer("created_at", { mode: "timestamp_ms" })
  .notNull()
  .default(sql`(unixepoch('now', 'subsec') * 1000)`);

////////////////////////////////////
// TABLES
////////////////////////////////////

export const users = sqliteTable("users", {
  id: ulid("id").primaryKey(),
  createdAt,

  username: text("username").notNull().unique(),
});

export const passkeyCredentials = sqliteTable("passkey_credentials", {
  id: text("id").primaryKey(), // It is generated by the WebAuthn library
  createdAt,

  userId: ulid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  publicKey: text("public_key").notNull(),
  counter: integer("counter").notNull(),
  transports: text("transports", { mode: "json" }).$type<
    AuthenticatorTransportFuture[]
  >(),
});

export const editors = sqliteTable("editors", {
  id: ulid("id").primaryKey(),
  createdAt,
});

export const images = sqliteTable("images", {
  id: ulid("id").primaryKey(),
  createdAt,

  editorId: ulid("editor_id")
    .notNull()
    .references(() => editors.id, { onDelete: "cascade" }),

  filename: text("filename").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull(),
  storageKey: text("storage_key").notNull().unique(),
});
